# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_or_birth',
            new_name='date_of_birth',
        ),
    ]
